gitlab_ssl_crt: |
  -----BEGIN CERTIFICATE-----
  MIIDlTCCAn2gAwIBAgIJAK+Ose+hs7C8MA0GCSqGSIb3DQEBCwUAMGExCzAJBgNV
  BAYTAlVTMQswCQYDVQQIDAJPSzEOMAwGA1UEBwwFVHVsc2ExETAPBgNVBAoMCFdp
  bGxpYW1zMSIwIAYDVQQDDBl0dWxweGdpdGFwMDEud2lsbGlhbXMuY29tMB4XDTE2
  MDgxNTE3MTgzMFoXDTE3MDgxNTE3MTgzMFowYTELMAkGA1UEBhMCVVMxCzAJBgNV
  BAgMAk9LMQ4wDAYDVQQHDAVUdWxzYTERMA8GA1UECgwIV2lsbGlhbXMxIjAgBgNV
  BAMMGXR1bHB4Z2l0YXAwMS53aWxsaWFtcy5jb20wggEiMA0GCSqGSIb3DQEBAQUA
  A4IBDwAwggEKAoIBAQDDHvHErtiWiqi2IrurIkS8MXsn742/jp2zi/MWRzdjDcjR
  1SIJ1U1gA+cVxbVLtMYb5OXW/nHTagQ+zYcY3TOSSGAxrBMxhGNS+JYhI4yPcYdZ
  a+HLnE/k7fRalV86vaxIZnJhhGejmLSOTkjw8z3m9HPTPQLBrxF4P7rQtOBgn+vZ
  BvEhayY8/jqGx5KUsVyF2rpVQYgBvFts2fy9GYruSTRagRZOGy4mL3mvnW/Ebdbj
  Bysx1x1nBy19kyd2eWtqa1HF89LxOHApdfwqOknEmMNWJNHStqfsFH6F07aEEWOq
  3ZkS1Qz73oZ22cW44oylr1Ss+9Xo7g/VJ2+0rmTbAgMBAAGjUDBOMB0GA1UdDgQW
  BBSJDAzt5rHrVVYtfNXaoxuwizDy6DAfBgNVHSMEGDAWgBSJDAzt5rHrVVYtfNXa
  oxuwizDy6DAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAJ8WmA83bD
  bSSXtBkwFnJv4Hx8Tl6/MCkbPMEhzoVusxVZshjRXnyNJOM5Av4c9g228UFn1RI/
  KA11UNL0seNnOzsMCR/TfPahXWwCzXGn7IdDvwntUmu5yEFeqX6FqkNqEsvW8ipQ
  JA+fiAcTMA3kFGNPEeDrOOpMv5Sr90JdX2/XMBPXTphohG60/6OrhrtYmCho3dCz
  ZVt+Rlv26/nTYvOYzJHawauQceKY77xaX6VTXARsK0jUQoq5A7BnP9i4SJvLKlB6
  bbjvRqo2MU1WVkY1DsxUAOsGtfx1Y1ts+14SSFthVQXP1oieteLF8mNMjRvnviX+
  rV5O1DZrCbBO
  -----END CERTIFICATE-----

