- name: Install GitLab
  hosts: git
  become: yes

  vars:
    gitlab_nginx_ssl_crt: "{{ gitlab_ssl_crt }}"
    gitlab_nginx_ssl_key: "{{ vault_gitlab_ssl_key }}"
    gitlab_nginx_redirect_http_to_https: True
    gitlab_ldap_enabled: True
    gitlab_ldap_servers:
      - name: gitlab_ldap_main
        provider_id: main
        label: 'Williams'
        host: 'gc-tulsa.williams.com'
        port: 636
        uid: 'sAMAccountName'
        method: 'ssl'
        bind_dn: 'CN=svc_redhatldap, OU=serviceaccts, OU=useraccts'
        password: "{{ vault_gitlab_ldap_main_password }}"
        active_directory: True
        allow_username_or_email_login: True
        base: 'DC=williams, DC=com'
        user_filter: ''

  roles:
    - gitlab
