- name: Install and configure VAS
  hosts: "{{ target_hosts | default ('all') }}"

  vars:
    vas_file_path: /var/lib/awx/files
    vas_file_name: qas_4_1_0_21708.tar.gz
    vas_user: sdoran
    vas_user_password: "{{ vault_vas_user_password }}"
    vas_domain: WILLIAMS.COM

  tasks:
    - name: Copy {{ vas_file_name }} to /var/tmp
      copy:
        src: "{{ vas_file_path }}/{{ vas_file_name }}"
        dest: /var/tmp
      tags:
        - vas

    - name: Unarchive file
      unarchive:
        src: /var/tmp/{{ vas_file_name }}
        dest: /opt/
        copy: no
      tags:
        - vas

    - name: Get VAS filename
      find:
        paths: /opt/
        patterns: QAS*
        file_type: directory
      register: vas_directory
      tags:
        - vas
        - always

    - name: Copy python-pip rpm
      copy:
        src: "{{ item }}"
        dest: /var/tmp
      with_fileglob:
        - "{{ vas_file_path }}/python-pip*"
      tags:
        - vas

    - name: Install PIP
      yum:
        name: /var/tmp/python-pip-7.1.0-1.el6.noarch.rpm
        state: present
      tags:
        - vas
        - always

    - name: Install pexpect
      pip:
        name: pexpect
      tags:
        - vas
        - always

    - name: Install VAS
      command: ./install.sh -q vasclnt vasgp
      args:
        chdir: "{{ vas_directory.files[0].path }}"
        creates: /etc/opt/quest/vas
      tags:
        - vas
        - vas_install

    - block:
      - name: Join VAS
        expect:
          command: ./install.sh join
          chdir: "{{ vas_directory.files[0].path }}"
          creates: /etc/opt/quest/vas/host.keytab
          responses:
              Would you like to join a different domain: 'yes'
              Do you wish to unjoin: 'yes'
              Please specify an AD user: "{{ vas_user }}@{{ vas_domain }}"
              join to: "{{ vas_domain }}"
              Please enter password: "{{ vas_user_password }}"
              '\(yes\|no\)\?': 'yes'
        tags:
          - vas
          - vas_install

      rescue:
        - name: Cleanup files
          file:
            path: /etc/opt/quest
            state: absent
          tags:
            - vas
            - vas_install
